In [1]:
import numpy as np

In [29]:
#matrix 1D
mat1D = np.array([1,2,3,4,5,6,7,8,9,10])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
print(mat1D)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
print(mat1D[0])

1


In [27]:
print(mat1D + 5)

[ 6  7  8  9 10 11 12 13 14 15]


In [31]:
print(mat2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(mat2D[0])
print(mat2D[1])
print(mat2D[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [35]:
print(mat2D[0] [2])

3


In [37]:
print(mat2D * 10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [39]:
print(mat1D.shape)
print(mat2D.shape)

(10,)
(3, 3)


In [41]:
print(mat1D.size)
print(mat2D.size)

10
9


In [67]:
#Spesial Matris
mZero = np.zeros((3,3))
mIdentity = np.eye((4))
mFull = np.full((4,4),7)
mOne = np.ones((5,4))
mRandomFloat = np.random.rand(5,5)
mRandomInt = np.random.randint(10,101, size=6)

In [53]:
print(mZero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [57]:
print(mIdentity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
print(mOne)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [65]:
print(mRandomFloat)

[[0.73028847 0.35505674 0.95162351 0.22133638 0.04807916]
 [0.4284577  0.9185604  0.03755137 0.92325336 0.43527153]
 [0.86803215 0.20032096 0.6533848  0.93798035 0.46758928]
 [0.03026857 0.58015951 0.81788045 0.83868316 0.91947153]
 [0.14072938 0.59411978 0.87539049 0.23254703 0.26122443]]


In [69]:
print(mRandomInt)

[49 52 72 93 38 81]


In [81]:
x = np.array([2,6,9])
y = np.array([1,3,5])

dotProduct = np.dot(x,y)
addMatrix = np.add(x,y)
minValue = np.min(x)
maxValue = np.max(y)
meanValue = np.mean(y)
medianValue = np.median(y)
stdValue = np.std(y)
print(dotProduct)
print(f"Hasil dari dot Product : {dotProduct}")
print(f"Hasil Penjumlahan matriks : {addMatrix}")
print(f"Nilai minimum dari {x} : {minValue}")
print(f"Nilai maksimum dari {y} : {maxValue}")
print(f"Rata-rata Nilai dari {y} : {meanValue}")
print(f"Nilai median dari {y} :{medianValue}")
print(f"Nilai Deviasi dari {y} : {stdValue}")

65
Hasil dari dot Product : 65
Hasil Penjumlahan matriks : [ 3  9 14]
Nilai minimum dari [2 6 9] : 2
Nilai maksimum dari [1 3 5] : 5
Rata-rata Nilai dari [1 3 5] : 3.0
Nilai median dari [1 3 5] :3.0
Nilai Deviasi dari [1 3 5] : 1.632993161855452


In [83]:
myArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

reshape = myArray.reshape(9,1)
flatten = myArray.flatten()

print(reshape)
print(flatten)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


In [85]:
#Filtering
nilaiSiswa = np.array([80,90,60,50,50,100,95])
lulus = nilaiSiswa[nilaiSiswa > 50]
jumlah = lulus.size
print(lulus)
print(f"Jumlah Siswa yang lulus:{jumlah}")

[ 80  90  60 100  95]
Jumlah Siswa yang lulus:5
